name : checking the calculator using python file

on : [push]
jobs:
   build: 
     runs-on : ubuntu-latest
     steps:
     - name: chekout code
       uses: actions/checkout@v2
     - name: setup python
       uses: actions/setup-python@v2
       with: 
          python-version: 3.9
     - name: install dependencies
       run : |
          python -m pip intall --upgrade pip
          pip install pytest
     - name: python scripting
       run: |
           python shell.py
     -  name: build and test
        run : | 
            pytest calc.py